# Generated by Django 3.2.9 on 2021-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_alter_moviereview_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
