# Generated by Django 3.2.9 on 2021-12-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RenameField(
            model_name='moviereview',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='movieinformation',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.moviereview'),
        ),
    ]
