# Generated by Django 3.2.9 on 2021-12-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_delete_movieinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
